### ISSUE TITLE
Image - Add a border for the image component

### ISSUE THREAD

**Issue by Blackbaud-ThomasOrtiz** [blackbaud/stache2#541]
An optional border would allow images to stand out from the background of the page better. 

### Expected behavior
![image-with-border](https://user-images.githubusercontent.com/35976987/46614803-bc947400-cae4-11e8-8468-28d3e10c61e4.PNG)

### Actual behavior
![image-without-border](https://user-images.githubusercontent.com/35976987/46614900-f796a780-cae4-11e8-8fcf-40768ebb2aaa.PNG)

### Temporary Solution
A user can add the following class to their `app.scss` and apply the class to an image

```scss
.image-border {
    .stache-image-object {
        border: 1px solid #cdcfd2 ;
    }
}
```
